services:
  redis:
    image: "redis:alpine"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis